// js/data.js — Project data, constellation zone definitions, and social links

export const PROJECTS = [
  {
    id: "odd-ai-reviewers",
    name: "odd-ai-reviewers",
    shortDesc: "AI code review pipeline",
    tagline: "Extensible AI code review pipeline with multi-agent analysis",
    category: "ai-devops",
    status: "active",
    isCluster: false,
    clusterMembers: null,
    constellation: "AI Reviewers",
    accentColor: "#9FE060",
    starSize: 2.33,
    position: [1.8, 1.0, -0.5],
    logoUrl: "assets/odd-ai-reviewers-banner.webp",
    mediaType: "youtube",
    mediaUrl: "https://youtu.be/rkDQ7ZA47XQ",
    screenshots: null,
    links: [
      {
        label: "GitHub",
        url: "https://github.com/oddessentials/odd-ai-reviewers",
        primary: true,
      },
      {
        label: "npm",
        url: "https://www.npmjs.com/package/@oddessentials/odd-ai-reviewers",
        primary: false,
      },
      { label: "Video", url: "https://youtu.be/rkDQ7ZA47XQ", primary: false },
    ],
  },
  {
    id: "ado-git-repo-insights",
    name: "ado-git-repo-insights",
    shortDesc: "Azure DevOps PR metrics",
    tagline:
      "Extract Azure DevOps PR metrics to SQLite with PowerBI-compatible dashboards",
    category: "data-devops",
    status: "active",
    isCluster: false,
    clusterMembers: null,
    constellation: "Analytics & Metrics",
    accentColor: "#38B000",
    starSize: 1.0,
    position: [-2.0, 0.5, 0.3],
    logoUrl: "assets/ado-git-repo-insights-logo.png",
    mediaType: "screenshots",
    mediaUrl: null,
    screenshots: [
      "assets/ado-git-repo-insights-screenshot-01.png",
      "assets/ado-git-repo-insights-screenshot-02.png",
      "assets/ado-git-repo-insights-screenshot-03.png",
    ],
    links: [
      {
        label: "Marketplace",
        url: "https://marketplace.visualstudio.com/items?itemName=OddEssentials.ado-git-repo-insights",
        primary: true,
      },
      {
        label: "GitHub",
        url: "https://github.com/oddessentials/ado-git-repo-insights",
        primary: true,
      },
      {
        label: "Demo",
        url: "https://oddessentials.github.io/ado-git-repo-insights/",
        primary: false,
      },
      {
        label: "PyPI",
        url: "https://pypi.org/project/ado-git-repo-insights/",
        primary: false,
      },
    ],
  },
  {
    id: "ado-git-repo-seeder",
    name: "ado-git-repo-seeder",
    shortDesc: "Azure DevOps test data",
    tagline:
      "Azure DevOps activity simulator — Node.js tool to seed realistic, multi-user Pull Request activity in Azure DevOps",
    category: "devops",
    status: "active",
    isCluster: false,
    clusterMembers: null,
    constellation: "Git Analytics",
    accentColor: "#3B5BDB",
    starSize: 0.89,
    position: [-1.2, 1.2, 0.1],
    logoUrl: null,
    mediaType: null,
    mediaUrl: null,
    screenshots: null,
    links: [
      {
        label: "GitHub",
        url: "https://github.com/oddessentials/ado-git-repo-seeder",
        primary: true,
      },
      { label: "Website", url: "https://oddessentials.com", primary: false },
    ],
  },
  {
    id: "repo-standards",
    name: "repo-standards",
    shortDesc: "Repo quality standards",
    tagline:
      "Authoritative JSON specification for repository quality standards across multiple stacks",
    category: "tooling",
    status: "active",
    isCluster: false,
    clusterMembers: null,
    constellation: "Repo Standards",
    accentColor: "#7B2CBF",
    starSize: 1.0,
    position: [2.2, -0.4, 0.2],
    logoUrl: null,
    mediaType: null,
    mediaUrl: null,
    screenshots: null,
    links: [
      {
        label: "GitHub",
        url: "https://github.com/oddessentials/repo-standards",
        primary: true,
      },
      {
        label: "npm",
        url: "https://www.npmjs.com/package/@oddessentials/repo-standards",
        primary: false,
      },
    ],
  },
  {
    id: "odd-self-hosted-ci",
    name: "odd-self-hosted-ci",
    shortDesc: "Self-hosted CI runtime",
    tagline:
      "Docker-first, provider-pluggable self-hosted CI runtime at zero cloud cost",
    category: "infrastructure",
    status: "active",
    isCluster: false,
    clusterMembers: null,
    constellation: "Self-Hosted Pipelines",
    accentColor: "#2EC4B6",
    starSize: 1.0,
    position: [-0.8, -1.2, -0.6],
    logoUrl: null,
    mediaType: null,
    mediaUrl: null,
    screenshots: null,
    links: [
      {
        label: "GitHub",
        url: "https://github.com/oddessentials/odd-self-hosted-ci-runtime",
        primary: true,
      },
      {
        label: "Docker Hub",
        url: "https://hub.docker.com/r/oddessentials/oscr-github",
        primary: false,
      },
      {
        label: "ADO Runner",
        url: "https://hub.docker.com/r/oddessentials/oscr-azure-devops",
        primary: false,
      },
    ],
  },
  {
    id: "odd-map",
    name: "odd-map",
    shortDesc: "Interactive office locator",
    tagline:
      "White-label interactive office locator with multi-provider rendering and region navigation",
    category: "frontend",
    status: "active",
    isCluster: false,
    clusterMembers: null,
    constellation: "Logistics",
    accentColor: "#F4A62A",
    starSize: 1.44,
    position: [0.3, 0.8, 0.5],
    logoUrl: null,
    mediaType: null,
    mediaUrl: null,
    screenshots: null,
    links: [
      {
        label: "Live Demo",
        url: "https://maps.oddessentials.com/",
        primary: true,
      },
      {
        label: "GitHub",
        url: "https://github.com/oddessentials/odd-map",
        primary: true,
      },
    ],
  },
  {
    id: "odd-fintech",
    name: "odd-fintech",
    shortDesc: "Financial intelligence dashboard",
    tagline:
      "Financial intelligence dashboard with real-time market data and congressional trade monitoring",
    category: "fintech",
    status: "active",
    isCluster: false,
    clusterMembers: null,
    constellation: "Market Data",
    accentColor: "#E63946",
    starSize: 2.33,
    position: [-2.2, -0.6, -0.3],
    logoUrl: "assets/odd-fintech-logo.webp",
    mediaType: "video",
    mediaUrl: "assets/odd-fintech-video.mp4",
    screenshots: null,
    links: [
      {
        label: "GitHub",
        url: "https://github.com/oddessentials/odd-fintech",
        primary: true,
      },
    ],
  },
  {
    id: "socialmedia-syndicator",
    name: "socialmedia-syndicator",
    shortDesc: "Social media syndication",
    tagline:
      "Admin-approved social media posts — Facebook & X Social Media post creator with admin approval",
    category: "application",
    status: "in-progress",
    isCluster: false,
    clusterMembers: null,
    constellation: "Social Media",
    accentColor: "#F0E442",
    starSize: 0.89,
    position: [1.5, 0.2, -0.2],
    logoUrl: null,
    mediaType: null,
    mediaUrl: null,
    screenshots: null,
    links: [
      {
        label: "GitHub",
        url: "https://github.com/oddessentials/socialmedia-syndicator",
        primary: true,
      },
      { label: "Website", url: "https://oddessentials.com", primary: false },
    ],
  },
  {
    id: "coney-island",
    name: "Coney Island Pottsville",
    shortDesc: "Restaurant ecosystem",
    tagline:
      "A 100+ year old family-owned restaurant with website, AI chat bot, and mobile app",
    category: "web",
    status: "active",
    isCluster: false,
    clusterMembers: [
      {
        name: "coney-website",
        description: "Restaurant website",
        url: "https://github.com/coneyislandpottsville/coney-website",
        status: "active",
      },
      {
        name: "yo-coney-bot",
        description: "AI-powered chat agent",
        url: "https://github.com/coneyislandpottsville/yo-coney-bot",
        status: "active",
      },
      {
        name: "yo-coney-mobile",
        description: "Mobile ordering app",
        url: "https://github.com/coneyislandpottsville/yo-coney-mobile",
        status: "active",
      },
    ],
    constellation: "Hospitality",
    accentColor: "#F68A2B",
    starSize: 1.44,
    position: [1.0, -1.0, 0.4],
    logoUrl: "assets/coney-island-logo-1024x690.svg",
    mediaType: "image",
    mediaUrl: "assets/coney-island-restaurant-and-tavern.jpg",
    screenshots: null,
    links: [
      {
        label: "Website",
        url: "https://coneyislandpottsville.com/",
        primary: true,
      },
      {
        label: "AI Chat",
        url: "https://chat.coneyislandpottsville.com/",
        primary: true,
      },
      {
        label: "Facebook",
        url: "https://facebook.com/coneyislandpottsville",
        primary: false,
      },
    ],
  },
  {
    id: "experiments-cluster",
    name: "Experiments",
    shortDesc: "Experimental projects",
    tagline: "Experimental and showcase projects exploring new ideas",
    category: "experiments",
    status: "active",
    isCluster: true,
    clusterMembers: [
      {
        name: "oddessentials-splash",
        description: "Main website of Odd Essentials, LLC",
        url: "https://github.com/oddessentials/oddessentials-splash",
        status: "active",
      },
      {
        name: "odd-portfolio",
        description: "Curated portfolio of all public Odd Essentials",
        url: "https://github.com/oddessentials/odd-portfolio",
        status: "active",
      },
      {
        name: "oddessentials-platform",
        description: "AI software expert open chat",
        url: "https://github.com/oddessentials/oddessentials-platform",
        status: "in-progress",
      },
      {
        name: "odd-demonstration",
        description: "Polyglot microservices demonstration",
        url: "https://github.com/oddessentials/odd-demonstration",
        status: "active",
      },
    ],
    constellation: "Experiments",
    accentColor: "#5A189A",
    starSize: 0.55,
    position: [-0.2, -0.5, 0.3],
    logoUrl: null,
    mediaType: null,
    mediaUrl: null,
    screenshots: null,
    links: [
      {
        label: "GitHub Org",
        url: "https://github.com/oddessentials",
        primary: true,
      },
    ],
  },
  {
    id: "dead-rock-cluster",
    name: "Reference Archive",
    shortDesc: "Paused reference projects",
    tagline: "Archived and paused reference repositories",
    category: "reference",
    status: "paused",
    isCluster: true,
    clusterMembers: [
      {
        name: "odd-hive-mind",
        description: "AI Coding Swarm",
        url: "https://github.com/oddessentials/odd-hive-mind",
        status: "paused",
      },
      {
        name: "oddessentials-mcp",
        description: "AI Tooling API",
        url: "https://github.com/oddessentials/oddessentials-mcp",
        status: "paused",
      },
      {
        name: "odd-repo-mapper",
        description: "AI Repo Mapper",
        url: "https://github.com/oddessentials/odd-repo-mapper",
        status: "paused",
      },
      {
        name: "odd-docs",
        description: "AI Repo Documenter",
        url: "https://github.com/oddessentials/odd-docs",
        status: "paused",
      },
      {
        name: "odd-dep-updater",
        description: "AI Repo Update",
        url: "https://github.com/oddessentials/odd-dep-updater",
        status: "paused",
      },
      {
        name: "odd-consultant",
        description: "AI Consultant",
        url: "https://github.com/oddessentials/odd-consultant",
        status: "paused",
      },
    ],
    constellation: "Archive",
    accentColor: "#6B7280",
    starSize: 0.55,
    position: [0.5, 1.3, -0.4],
    logoUrl: null,
    mediaType: null,
    mediaUrl: null,
    screenshots: null,
    links: [
      {
        label: "GitHub Org",
        url: "https://github.com/oddessentials",
        primary: true,
      },
    ],
  },
];

export const CONSTELLATION_ZONES = [
  {
    name: "DevOps & Engineering",
    scrollStart: 0.0,
    scrollEnd: 0.33,
    projectIds: [
      "odd-ai-reviewers",
      "ado-git-repo-insights",
      "ado-git-repo-seeder",
      "repo-standards",
      "odd-self-hosted-ci",
    ],
    nebulaHue: "green",
    nebulaHueRgb: [0.22, 0.69, 0.0],
    hex: "#38B000",
    hexBright: "#9FE060",
    hexWatermark: "#5A8A50",
    statusText: "Tracing the DevOps pipeline...",
  },
  {
    name: "Applications & Products",
    scrollStart: 0.33,
    scrollEnd: 0.66,
    projectIds: [
      "odd-map",
      "odd-fintech",
      "socialmedia-syndicator",
      "coney-island",
      "repo-standards",
    ],
    nebulaHue: "amber",
    nebulaHueRgb: [0.96, 0.65, 0.16],
    hex: "#F4A62A",
    hexBright: "#F0E442",
    hexWatermark: "#A89B60",
    statusText: "Viewing applications & products...",
  },
  {
    name: "Prototypes",
    scrollStart: 0.66,
    scrollEnd: 1.0,
    projectIds: ["experiments-cluster", "dead-rock-cluster", "repo-standards"],
    nebulaHue: "purple",
    nebulaHueRgb: [0.48, 0.17, 0.75],
    hex: "#7B2CBF",
    hexBright: "#9B4DDF",
    hexWatermark: "#6B5A80",
    statusText: "Exploring prototypes...",
  },
];

export const SOCIAL_LINKS = [
  { platform: "LinkedIn", url: "https://www.linkedin.com/in/petepalles/" },
  { platform: "Facebook", url: "https://www.facebook.com/oddessentials" },
  { platform: "X", url: "https://x.com/odd_essentials" },
  { platform: "GitHub", url: "https://github.com/oddessentials" },
  { platform: "NPM", url: "https://www.npmjs.com/search?q=@oddessentials" },
  { platform: "PyPI", url: "https://pypi.org/user/oddessentials/" },
  { platform: "Docker Hub", url: "https://hub.docker.com/u/oddessentials" },
  {
    platform: "VS Marketplace",
    url: "https://marketplace.visualstudio.com/publishers/OddEssentials",
  },
  { platform: "Codecov", url: "https://app.codecov.io/github/oddessentials" },
  { platform: "Medium", url: "https://medium.com/@pete.palles" },
  { platform: "Gravatar", url: "https://gravatar.com/really3675c8a1ca" },
];
